import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import type { PropsWithChildren } from "react";

import "~/assets/css/globals.css";
import { ThemeProvider } from "~/components/theme-provider";
import { Toaster } from "~/components/ui/sonner";
import { ReactQueryProvider } from "~/libs/react-query/provider";
import { cn } from "~/libs/utils";

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      sizes: "32x32",
      type: "image/png",
      url: "/favicon.png",
    },
  ],
  title: "Frontend Mentor | Kanban task management web app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn("font-sans", fontSans.variable)}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster richColors />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
